portfolio/Models/Skill.cs
using System.ComponentModel.DataAnnotations;

namespace portfolio.Models
{
    public class Skill
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        [Range(0,100)]
        public int ProficiencyLevel { get; set; }
    }
}

portfolio/Controllers/SkillController.cs
using Microsoft.AspNetCore.Mvc;
using portfolio.Data;
using portfolio.Models;

namespace portfolio.Controllers
{
    public class SkillController : Controller
    {
        private ApplicationDbContext _db;
        public SkillController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            List<Skill> skillList = _db.Skills.ToList();
            return View(skillList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Skill obj)
        {
            if (ModelState.IsValid)
            {
                _db.Skills.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            List<Skill> skillList = _db.Skills.ToList();
            return View(skillList);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Skill categoryFromDb = _db.Skills.Find(id);
            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }
        [HttpPost]
        public IActionResult Edit(Skill obj)
        {
            if (ModelState.IsValid)
            {
                _db.Skills.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }


        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Skill categoryFromDb = _db.Skills.Find(id);
            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }


        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int id)
        {
            Skill obj = _db.Skills.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Skills.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");

            if (ModelState.IsValid)
            {
                _db.Skills.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

portfolio/Views/Skill/Create.cshtml
<link rel="stylesheet" href="~/css/createskill.css" />

@model Skill

<div id="login-form-wrap">
    <h2>Create Skill</h2>
    <form method="post" id="login-form">
        <p>
            <input asp-for="Name" type="text" id="username" placeholder="Name" required>
            <i class="validation"><span></span><span></span></i>
        </p>
        <p>
            <input asp-for="ProficiencyLevel" type="number" id="email" placeholder="Proficiency Level" required><i class="validation"><span></span><span></span></i>
        </p>
        <p>
            <input type="submit" id="login" value="Create Skill">
        </p>
    </form>
    
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

portfolio/Views/Skill/Delete.cshtml
<link rel="stylesheet" href="~/css/createskill.css" />

@model Skill

<div id="login-form-wrap">
    <h2>Create Skill</h2>
    <form method="post" id="login-form">
        <p style="padding:20px">
            <input asp-for="Name" type="text" id="username" placeholder="Name" required disabled>
            <i class="validation"><span></span><span></span></i>
        </p>
        <p style="padding:20px">
            <input asp-for="ProficiencyLevel" type="number" id="email" placeholder="Proficiency Level" required disabled><i class="validation"><span></span><span></span></i>
        </p>
        <p style="padding:20px">
            <input type="submit" id="login" value="Delete Skill">
        </p>
    </form>

</div>

portfolio/Views/Skill/Edit.cshtml
<link rel="stylesheet" href="~/css/createskill.css" />

@model Skill

<div id="login-form-wrap">
    <h2>Create Skill</h2>
    <form method="post" id="login-form">
        <p style="padding:20px" >
            <input asp-for="Name" type="text" id="username" placeholder="Name" required>
            <i class="validation"><span></span><span></span></i>
        </p>
        <p style="padding:20px">
            <input asp-for="ProficiencyLevel" type="number" id="email" placeholder="Proficiency Level" required><i class="validation"><span></span><span></span></i>
        </p>
        <p style="padding:20px">
            <input type="submit" id="login" value="Update Skill">
        </p>
    </form>

</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

portfolio/Views/Skill/Index.cshtml
@model List<Skill>


<link rel="stylesheet" href="~/css/skill.css" />

<div class="container-skillbar">
    @if (User.Identity.IsAuthenticated)
    {
        <a style="margin-bottom:25px;color:white" asp-controller="Skill" asp-action="Create"> <i class="fa-solid fa-plus"> Create Skill</i> </a>
    }
    
    @foreach(var skill in Model)
    {
        <div class="skillbar clearfix " data-percent="85%">
            <div class="skillbar-title" style="background: #970cc1;"><span>@skill.Name</span></div>
            <div class="skillbar-bar one"></div>
            <div class="skill-bar-percent">@skill.ProficiencyLevel%</div>
        </div>
        @if (User.Identity.IsAuthenticated)
        {
            <div style="margin-bottom:25px; margin-top:0px">
                <a style="text-decoration:none;color:white" asp-route-id="@skill.Id" asp-action="Edit" asp-controller="Skill">Edit</a>
                <span style="color:white">|</span>
                <a style="text-decoration:none;color:white" asp-route-id="@skill.Id" asp-action="Delete" asp-controller="Skill">Delete</a>
            </div>
        }
    }
</div>
      
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src="https://kit.fontawesome.com/74456a4746.js"
        crossorigin="anonymous"></script>
      